# Font shenannigans:
font_family		JetBrainsMono Nerd Font
bold_font		auto
italic_font		auto
bold_italic_font	auto
font_size		12.0

# Cursor configs:
cursor_shape		beam
cursor_blink_interval	0

# Window stuff:
background_opacity	0.8
confirm_os_window_close	0
window_padding_width	8

# Scroll:
scrollback_lines	10000
enable_audio_bell	no

tab_bar_edge		top
tab_bar_style		powerline


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
