
set -g default-terminal "screen-256color"

bind r source-file ~/.dotfiles/config/tmux/tmux.conf \; display-message "Config reloaded!"

# Convenient window/pane creation
bind  c  new-window      -c "#~" #New windows default to $HOME
bind  %  split-window -h -c "#{pane_current_path}" # Panes keep $PWD
bind '"' split-window -v -c "#{pane_current_path}"

setw -g automatic-rename on
set -g renumber-windows on
